services:
  postgresql:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: scrapper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql:/var/lib/postgresql/data
  liquibase-migrations:
    image: liquibase/liquibase:4.25
    command:
      - --search-path=/liquibase/changelog/liquibase/changelog
      - --changelog-file=master.yaml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/scrapper
      - --username=postgres
      - --password=postgres
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    depends_on:
      - postgresql

volumes:
  postgresql: { }
  pgadmin: { }
  liquibase-migrations: { }

networks:
  backend: { }
