app:
  scheduler:
    enable: true
    interval: 30000
    force-check-delay: 10000
  linkDelay: 5
  limitPerCheck: 10
  database-access-type: jooq
  retryable-config:
    status-codes: 429, 403, 404
    backoff-type: exponent
  bucket-config:
    tokens: 100
    millis-of-refill: 1000
    refill-tokens: 1
  use-queue: true
  kafka-configuration:
    bootstrap-servers: localhost:9091
    topic-name: messages.protobuf

management:
  server:
    port: 7777
  endpoints:
    web:
      base-path: "/"
      exposure:
        include: "info,prometheus"
      path-mapping:
        prometheus: "metrics"
  swagger-ui:
    path: /swagger-ui
  metrics:
    tags:
      application: ${spring.application.name}

spring:
  liquibase:
    enabled: false
  application:
    name: scrapper
  datasource:
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_NAME}
    url: ${JDBC_URL}
  jpa:
    hibernate:
      ddl-auto: validate


server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
