app:
  scheduler:
    enable: true
    interval: 10000
    force-check-delay: 10000
  linkDelay: 5
  limitPerCheck: 10
  database-access-type: jooq
  retryable-config:
    status-codes: 429, 403, 404
    backoff-type: exponent
  bucket-config:
    tokens: 100
    millis-of-refill: 1000
    refill-tokens: 1
  use-queue: true
  bootstrap-servers: localhost:9091

springdoc:
  swagger-ui:
    path: /swagger-ui

spring:
  liquibase:
    enabled: false
  application:
    name: scrapper
  datasource:
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_NAME}
    url: ${JDBC_URL}
  jpa:
    hibernate:
      ddl-auto: validate


server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
