app:
  scheduler:
    enable: true
    interval: 10000
    force-check-delay: 10000

springdoc:
  swagger-ui:
    path: /swagger-ui

spring:
  liquibase:
    enabled: false
  application:
    name: scrapper
  datasource:
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_NAME}
    url: ${JDBC_URL}

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
