app:
  scheduler:
    enable: true
    interval: 10000
    force-check-delay: 10000
  linkDelay: 5
  limitPerCheck: 10
  database-access-type: jooq

springdoc:
  swagger-ui:
    path: /swagger-ui

spring:
  liquibase:
    enabled: false
  application:
    name: scrapper
  datasource:
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_NAME}
    url: ${JDBC_URL}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true


server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

  level:
    org:
      jooq:
        tools:
          LoggerListener: DEBUG
