global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
  - job_name: "spring"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - host.docker.internal:7778
          - host.docker.internal:7777
