app:
  telegramToken: ${TELEGRAM_KEY}
  telegramName: ${TELEGRAM_NAME}
  retryable-config:
    backoff-type: linear
    status-codes: 429
  kafka-configuration:
    bootstrap-servers: localhost:29091
    topic-name: messages.protobuf
    group-id: messages-group
    dlq-configuration:
      interval-between-attempts: 1000
      max-attempts-before-dlq: 3
      name: messages.protobuf-dlq

management:
  server:
    port: 7778
  endpoints:
    web:
      base-path: "/"
      exposure:
        include: "info,prometheus"
      path-mapping:
        prometheus: "metrics"
  metrics:
    tags:
      application: ${spring.application.name}

springdoc:
  swagger-ui:
    path: /swagger-ui

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
