app:
  telegramToken: ${TELEGRAM_KEY}
  telegramName: ${TELEGRAM_NAME}
  retryable-config:
    backoff-type: linear
    status-codes: 429

springdoc:
  swagger-ui:
    path: /swagger-ui

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
