/*
 * This file is generated by jOOQ.
 */

package edu.java.domain.jooq.tables;

import edu.java.domain.jooq.tables.tables.Databasechangeloglock;
import edu.java.domain.jooq.tables.tables.Links;
import edu.java.domain.jooq.tables.tables.Users;
import edu.java.domain.jooq.tables.tables.UsersLinks;
import java.util.Arrays;
import java.util.List;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Public extends SchemaImpl {

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();
    private static final long serialVersionUID = 1L;
    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.links</code>.
     */
    public final Links LINKS = Links.LINKS;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * The table <code>public.users_links</code>.
     */
    public final UsersLinks USERS_LINKS = UsersLinks.USERS_LINKS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }

    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Databasechangeloglock.DATABASECHANGELOGLOCK,
            Links.LINKS,
            Users.USERS,
            UsersLinks.USERS_LINKS
        );
    }
}
