/*
 * This file is generated by jOOQ.
 */

package edu.java.domain.jooq.tables;

import edu.java.domain.jooq.tables.tables.Databasechangeloglock;
import edu.java.domain.jooq.tables.tables.Links;
import edu.java.domain.jooq.tables.tables.Users;
import edu.java.domain.jooq.tables.tables.UsersLinks;

/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.links</code>.
     */
    public static final Links LINKS = Links.LINKS;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;

    /**
     * The table <code>public.users_links</code>.
     */
    public static final UsersLinks USERS_LINKS = UsersLinks.USERS_LINKS;
}
