/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.tables.tables.records;


import edu.java.domain.jooq.tables.tables.Links;

import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LinksRecord extends UpdatableRecordImpl<LinksRecord> implements Record4<Long, String, OffsetDateTime, OffsetDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.links.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.links.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.links.link</code>.
     */
    public void setLink(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.links.link</code>.
     */
    public String getLink() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.links.updatetime</code>.
     */
    public void setUpdatetime(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.links.updatetime</code>.
     */
    public OffsetDateTime getUpdatetime() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.links.lastsendtime</code>.
     */
    public void setLastsendtime(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.links.lastsendtime</code>.
     */
    public OffsetDateTime getLastsendtime() {
        return (OffsetDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, OffsetDateTime, OffsetDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, String, OffsetDateTime, OffsetDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Links.LINKS.ID;
    }

    @Override
    public Field<String> field2() {
        return Links.LINKS.LINK;
    }

    @Override
    public Field<OffsetDateTime> field3() {
        return Links.LINKS.UPDATETIME;
    }

    @Override
    public Field<OffsetDateTime> field4() {
        return Links.LINKS.LASTSENDTIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getLink();
    }

    @Override
    public OffsetDateTime component3() {
        return getUpdatetime();
    }

    @Override
    public OffsetDateTime component4() {
        return getLastsendtime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getLink();
    }

    @Override
    public OffsetDateTime value3() {
        return getUpdatetime();
    }

    @Override
    public OffsetDateTime value4() {
        return getLastsendtime();
    }

    @Override
    public LinksRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public LinksRecord value2(String value) {
        setLink(value);
        return this;
    }

    @Override
    public LinksRecord value3(OffsetDateTime value) {
        setUpdatetime(value);
        return this;
    }

    @Override
    public LinksRecord value4(OffsetDateTime value) {
        setLastsendtime(value);
        return this;
    }

    @Override
    public LinksRecord values(Long value1, String value2, OffsetDateTime value3, OffsetDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LinksRecord
     */
    public LinksRecord() {
        super(Links.LINKS);
    }

    /**
     * Create a detached, initialised LinksRecord
     */
    public LinksRecord(Long id, String link, OffsetDateTime updatetime, OffsetDateTime lastsendtime) {
        super(Links.LINKS);

        setId(id);
        setLink(link);
        setUpdatetime(updatetime);
        setLastsendtime(lastsendtime);
        resetChangedOnNotNull();
    }
}
